### ISSUE TITLE
"nc" of response message is padding with 2 "00"

### ISSUE THREAD

**Issue by zerodice0** [atomx/nginx-http-auth-digest#11]
So some language, like c/c++, is recognized to EOF.
I guess it is caused by no \", then I added. :) Plz check this.

**Comment by erikdubbelboer** [comment]
Since `nc` is just a number it shouldn't matter if it's enclosed in quotes or not. Can you show me the case where this matters? I'm guessing you have some C/C++ library that parses the header incorrectly?

**Comment by zerodice0** [comment]
I'm sorry but look 812 line.
`"qop=\"auth\", rspauth=\"%*s\", cnonce=\"%*s\", nc=%*s"`
'NC' is not number, it is string. So if field->nc.len is not correct, then compiler fill 0 padding after real nc value. :(

**Comment by erikdubbelboer** [comment]
I looked into it again. The only way I can see this happening is if your request actually contains an `nc` with `\0` in it. `field->nc.len` will always be correct. Anyways your patch does fix this if it happens and doesn't hurt anything, so I merged it. Thanks :)

Your english is more than good enough :)

**Comment by zerodice0** [comment]
I got it. I'll check it again, too. Thanks :)
