### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by sledz** [atomx/nginx-http-auth-digest#16]
Some plans to release a version?

Or at least to tag a suggested version?

This would be very helpful. After all this project is referenced from the [official NGINX project](https://www.nginx.com/resources/wiki/modules/auth_digest/).

**Comment by erikdubbelboer** [comment]
I have tagged [v1.0.0](https://github.com/atomx/nginx-http-auth-digest/tree/v1.0.0). Thanks for the suggestion and the link to the official page, I had no idea that existed.
