### ISSUE TITLE
nginx-http-auth-digest does not process variables in auth_digest

### ISSUE THREAD

**Issue by borkhuis** [atomx/nginx-http-auth-digest#7]
I want to use optional authentication. For this I check if the password file exists and if so I set a variable to the realm I want to use, otherwise it is set to off.This variable is used as a parameter for auth_digest. However, this variable is not parsed by the module.

I created a fix for this problem, see attached patch. The problem was that the realm was just read, not processed. With this patch the variable is expanded. I can now create or remove a password file and the module will behave depending on this file.

[ngx_http_auth_digest_module.patch.zip](https://github.com/atomx/nginx-http-auth-digest/files/698198/ngx_http_auth_digest_module.patch.zip)

The commands I use in the nginx configuration file are:
```
    # Check if password file exists.
    # Default is authentication off
    set $authfile /etc/nginx/extra.htpasswd;
    set $authmode off;
    if (-f $authfile) {
        # Password file exists, enable authentication
        set $authmode Password;
    }
    auth_digest $authmode;
    auth_digest_user_file $authfile;
```

**Comment by erikdubbelboer** [comment]
@borkhuis I see you just forked the repo. I'm about to commit a fix for this issue after some testing.

**Comment by borkhuis** [comment]
@erikdubbelboer Thanks for the message. I was just playing aroung with Github and trying to test the fork mechanism instead of the patch-file. I don't have much experience with Git yet, so just experimenting a bit.
BTW: thanks for picking up this issue this fast.

**Comment by erikdubbelboer** [comment]
@borkhuis can you try the version I just pushed?

**Comment by borkhuis** [comment]
@erikdubbelboer Change has been tested and works. Thanks for the quick fix!
